version: "3.9"

services:
  redis:
    image: "redis:7.0.2"
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: "redis-server --save 60 1 --loglevel warning"

  bot:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8443:8443"
    environment:
      - POKERBOT_TOKEN=$POKERBOT_TOKEN
      - POKERBOT_REDIS_HOST=redis
      - POKERBOT_PREFERRED_MODE=${POKERBOT_PREFERRED_MODE:-webhook}
      - POKERBOT_WEBHOOK_LISTEN=${POKERBOT_WEBHOOK_LISTEN:-0.0.0.0}
      - POKERBOT_WEBHOOK_PORT=${POKERBOT_WEBHOOK_PORT:-8443}
      - POKERBOT_WEBHOOK_PATH=${POKERBOT_WEBHOOK_PATH:-/telegram/webhook}
      - POKERBOT_WEBHOOK_PUBLIC_URL=${POKERBOT_WEBHOOK_PUBLIC_URL}
      - POKERBOT_WEBHOOK_SECRET=${POKERBOT_WEBHOOK_SECRET:-}

volumes:
  redis_data:
